language: ruby
sudo: false
cache: bundler
bundler_args: --without console
script:
  - bundle exec rspec
  - bundle exec rubocop
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
